const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const SET_CURRENT = 'SET_CURRENT';
const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
const ADD_PHONE_NUMBER = 'ADD_PHONE_NUMBER';
const ADD_USER_NAME = 'ADD_USER_NAME';
const ADD_BIO = 'ADD_BIO';
const ADD_PROPOSER = 'ADD_PROPOSER';
const MARITAL_STATUS = 'MARITAL_STATUS';
const ADD_PERSONAL_INFO = 'ADD_PERSONAL_INFO';
const ADD_WORK_DETAIL = 'ADD_WORK_DETAIL';
const HAS_CHILD = 'HAS_CHILD';
const ADD_CHILD_DETAIL = 'ADD_CHILD_DETAIL';
const REQUIRED_MEMBER = 'REQUIRED_MEMBER';
const ADD_MEMBER_DETAIL = 'ADD_MEMBER_DETAIL';
const ADD_FAMILY_DETAIL = 'ADD_FAMILY_DETAIL';
const HAS_LIABILITY = 'ADD_LIABILITY';
const ADD_LIABILITY = 'ADD_LIABILITY';
const HAS_ASSETS = 'ADD_ASSETS';
const ADD_ASSETS = 'ADD_ASSETS';
const HAS_ADDITIONAL_INFO = 'ADD_ADDITIONAL_INFO';
const ADD_ADDITIONAL_INFO = 'ADD_ADDITIONAL_INFO';
const ADD_LIFE_INSURANCE = 'ADD_LIFE_INSURANCE';
const ADD_HEALTH_INSURANCE = 'ADD_HEALTH_INSURANCE';
const HAS_LIFE_INSURANCE = 'HAS_LIFE_INSURANCE';
const HAS_HEALTH_INSURANCE = 'HAS_HEALTH_INSURANCE';
const HAS_TI_COVER = 'HAS_TI_COVER';
const ADD_TI_COVER = 'ADD_TI_COVER';
const HAS_CI_COVER = 'HAS_CI_COVER';
const ADD_CI_COVER = 'ADD_CI_COVER';
const HAS_PD_COVER = 'HAS_PD_COVER';
const ADD_PD_COVER = 'ADD_PD_COVER';
const ADD_HOME_INSURANCE = 'ADD_HOME_INSURANCE';
const HAS_MOTOR_VEHICLE = 'HAS_MOTOR_VEHICLE';
const ADD_MOTOR_VEHICLE = 'ADD_MOTOR_VEHICLE';
const HAS_MOTOR_INSURANCE = 'HAS_MOTOR_INSURANCE';
const ADD_MOTOR_INSURANCE = 'ADD_MOTOR_INSURANCE';
const GET_PROPOSAL_ID = 'GET_PROPOSAL_ID';
const SET_PROPOSAL_ID = 'SET_PROPOSAL_ID';
const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
const GET_RESULT_MODULE1 = 'GET_RESULT_MODULE1';
const GET_RESULT_MODULE2 = 'GET_RESULT_MODULE2';
const GET_RESULT_MODULE3 = 'GET_RESULT_MODULE3';
const GET_RESULT_MODULE4 = 'GET_RESULT_MODULE4';
const GET_RESULT_MODULE5 = 'GET_RESULT_MODULE5';
const GET_RESULT_MODULE6 = 'GET_RESULT_MODULE6';
const LOAD_RESULT_MODULE = 'LOAD_RESULT_MODULE';

export default {
  INCREMENT,
  DECREMENT,
  SET_CURRENT,
  ADD_PHONE_NUMBER,
  ADD_USER_NAME,
  ADD_BIO,
  ADD_PROPOSER,
  MARITAL_STATUS,
  ADD_PERSONAL_INFO,
  ADD_WORK_DETAIL,
  HAS_CHILD,
  ADD_CHILD_DETAIL,
  REQUIRED_MEMBER,
  ADD_MEMBER_DETAIL,
  ADD_FAMILY_DETAIL,
  HAS_LIABILITY,
  ADD_LIABILITY,
  HAS_ASSETS,
  ADD_ASSETS,
  HAS_ADDITIONAL_INFO,
  ADD_ADDITIONAL_INFO,
  ADD_LIFE_INSURANCE,
  ADD_HEALTH_INSURANCE,
  HAS_TI_COVER,
  HAS_CI_COVER,
  HAS_PD_COVER,
  ADD_TI_COVER,
  ADD_CI_COVER,
  ADD_PD_COVER,
  HAS_LIFE_INSURANCE,
  HAS_HEALTH_INSURANCE,
  ADD_HOME_INSURANCE,
  ADD_MOTOR_VEHICLE,
  ADD_MOTOR_INSURANCE,
  HAS_MOTOR_VEHICLE,
  HAS_MOTOR_INSURANCE,
  GET_PROPOSAL_ID,
  SET_PROPOSAL_ID,
  SET_AUTHENTICATED,
  INCREMENT_ASYNC,
  LOAD_RESULT_MODULE,
  GET_RESULT_MODULE1,
  GET_RESULT_MODULE2,
  GET_RESULT_MODULE3,
  GET_RESULT_MODULE4,
  GET_RESULT_MODULE5,
  GET_RESULT_MODULE6
};